development:
  host: localhost
  database: falling_block_rpg_server_development

test:
  host: localhost
  database: falling_block_rpg_server_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
